### ISSUE TITLE
Line highlights don't work

### ISSUE THREAD

**Issue by FichteFoll** [sublimetext-io/docs.sublimetext.io#17]
Per the vuepress documentation, we should be able to add line highlights, but they don't seem to work (in #16 at least – not sure if there are used anywhere else).

References:
- https://vuepress.vuejs.org/guide/markdown.html#line-highlighting-in-code-blocks
- https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown/lib/highlightLines.js

**Comment by rchl** [comment]
Looks like the `markdown-it-attrs` plugin creates this problem.
I suppose it consumes those markers itself for its own purposes but I'm not sure how this system works. Probably worth creating an issue at its repo.

**Comment by TerminalFi** [comment]
Fixed with migration to Vitepress

**Comment by FichteFoll** [comment]
https://docs.sublimetext.io/guide/extensibility/plugins/input_handlers.html#the-next-input-method

![2023-10-29_15-52-17](https://github.com/sublimetext-io/docs.sublimetext.io/assets/931051/757df5d9-4600-4596-b4a3-16b49f861286)
