### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by TheSecEng** [sublimetext-io/docs.sublimetext.io#2]
**What**
Should we update the _Google Analytics_ setup for this? Or should we remove it.

1. Do we care about how people are locating the website?
2. Do we want to track the amount of traffic that we are experiencing?

```html
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20962303-1']);
  _gaq.push(['_setDomainName', '.sublimetext.info']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
```

**Comment by TheSecEng** [comment]
@FichteFoll thoughts?

**Comment by FichteFoll** [comment]
I already had them open in a tab to remove them later while I was going through the `http://` links. Removed in https://github.com/sublimetext-io/docs.sublimetext.io/commit/77c648faef7c845c6419f8eef742b7cb23ca8669.
