### ISSUE TITLE
How does the First Plugin example work?

### ISSUE THREAD

**Issue by sharun-s** [sublimetext-io/docs.sublimetext.io#22]
Referring to file - https://github.com/sublimetext-io/docs.sublimetext.io/blob/master/docs/guide/extensibility/plugins/README.md

The first plugin section asks the reader to save the file as hello_world.py. 
Names the class - ExampleCommand.
Runs the command - view.run_command('example')

How does sublime connect the string 'example' with the file hello_world.py and class ExampleCommand? Isn't clear how this mapping is happening. Can it be clarified? Thanks!

**Comment by jfcherng** [comment]
https://github.com/sublimetext-io/docs.sublimetext.io/blob/master/docs/guide/extensibility/plugins/README.md#conventions-for-command-names

**Comment by FichteFoll** [comment]
Rendered on the site: https://docs.sublimetext.io/guide/extensibility/plugins/#conventions-for-command-names

**Comment by jfcherng** [comment]
Interesting, the anchor `#conventions-for-command-names` in the link doesn't seem to work. My Chrome doesn't jump to that section.

**Comment by sharun-s** [comment]
@FichteFoll thats a great addition. Thanks. Clarifies things! And thanks for the docs. Really useful.
 
It took me a long time to get what was doing on cause I saved my first example file as multifilereplace.py and and trying to implement a sample command called MultiFileReplaceCommand. Had no clue why it was failing. And kept thinking my code was throwing a silent error or something. 
Took a while to find other samples in the Default package directory to make the connection.

**Comment by FichteFoll** [comment]
> Interesting, the anchor `#conventions-for-command-names` in the link doesn't seem to work. My Chrome doesn't jump to that section.

@jfcherng it works for me on FireFox. If you can reliably reproduce it, please open a new issue.
