### ISSUE TITLE
The search field doesn't do what I want

### ISSUE THREAD

**Issue by rwols** [sublimetext-io/docs.sublimetext.io#29]
It should guide me to:

- a built-in command when I type the name of that command
- a global setting when I type the name of a setting

**Comment by jrappen** [comment]
The built-in search via the plug-in:

- https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/plugin-search
- https://vuepress.vuejs.org/plugin/official/plugin-search.html

only includes headers. One solution would be to have a section with its own header per documented command or setting.

**Comment by TerminalFi** [comment]
This now is more inline with expectations using Algolia
