### ISSUE TITLE
Documentation on mousemap files.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [sublimetext-io/docs.sublimetext.io#31]
Currently, the community docs lacks information on mousemap files (and the official docs also don't have any information on them).
I have made a small gist of whatever I know about them here :- https://gist.github.com/Ultra-Instinct-05/e1ca9a4d48641cc6c0af46fec0010611
May be this can be used as a starting point for some concrete information on mousemap files.

**Comment by FichteFoll** [comment]
Mousemap files have been on the agenda previously but have little priority because I believe the default mousmap file(s) to be self-explanatory. Regardless, if we strive to provide complete documentation, they should definitely be explained, if only for the fact that we can't specify contexts.
