### ISSUE TITLE
Dev server requires a lot of restarts

### ISSUE THREAD

**Issue by FichteFoll** [sublimetext-io/docs.sublimetext.io#34]
When working on the initial config.js, I had to restart the local dev server a lot because vuepress couldn't handle the config changes it appeared. I don.t think there is an immediate solution to that, but I wanted to track it as an issue for myself at least.

The vuepress devs have been working on vite and [vitepress](https://github.com/vuejs/vitepress) for a while, which is probably worth monitoring, as it follows the same principles but promises to work on exactly these pain points of vue.

**Comment by rchl** [comment]
I'll throw in another option to the mix: https://content.nuxtjs.org/

(I'm quite close to the Nuxt ecosystem so maybe I'm biased).

**Comment by jrappen** [comment]
There's also work being done on vuepress v2.

- https://github.com/vuejs/vuepress
    - built on vue2
- https://github.com/vuepress/vuepress-next
    - built on vue3
    - refactored with TypeScript
- https://github.com/vuejs/vitepress
    - built on https://github.com/vitejs/vite

**Comment by TerminalFi** [comment]
This seems not to be an issue in Vitepress.

**Comment by FichteFoll** [comment]
Indeed, vitepress can figure out by itself when it needs a restart and … just does that in less than a second. Very nice experience.
