### ISSUE TITLE
How to write java code with sublime Text3

### ISSUE THREAD

**Issue by zhenghanwen** [sublimetext-io/docs.sublimetext.io#36]
Now, I have a problem. When writing java code, I need to introduce selenium related jars. I don't know how to introduce it into the project.

**Comment by FichteFoll** [comment]
This isn't a place for questions or discussion. If they are related to Sublime Text, I suggest asking on the forum or the discord server. https://forum.sublimetext.com/t/resources-and-bug-tracking/22985
