### ISSUE TITLE
How to open tabs for editing files?

### ISSUE THREAD

**Issue by thistlillo** [sublimetext-io/docs.sublimetext.io#51]
I have just installed Sublime Text 3 on Windows 10. After opening a folder, my simple mind cannot figure out the criteria used by ST3 to open new tabs for files: I am able to browse through my source code with the various goto anywhere, symbols, etc (fantastic), but I cannot open two tabs with two files.

Better said: I can. 
- If I select a file f1 in a folder and a file f2 in another folder, the ST3 open two tabs, one per file.
- If I have one tab and modify the content, then I can open a new file.

But: how can I open, for example, three different tabs without modifying any of them? If I open a file in a folder and do not modify it, all the other files in the same folder are assigned to the same tab of the first file.

I looked for this information both on the official website and here, but could not find any info.

Please don't get upset if the question is too silly, but -really- I got exhausted trying to figure out the algorithm.

**Comment by frou** [comment]
It sounds like you are probably single-clicking files in the sidebar. Sublime Text with default settings will only "preview" files that are single-clicked. To open a file permanently in its own tab if should be double-clicked in the sidebar.

**Comment by FichteFoll** [comment]
This appears to have been answered. We could probably explain file navigation a bit better in some areas, especially with ST4 now out, but I don't want to track that in this issue.
