### ISSUE TITLE
'clear_recent_files' command not working

### ISSUE THREAD

**Issue by xianghongai** [sublimetext-io/docs.sublimetext.io#52]
Default.sublime-commands
```
[
    { "caption": "Open Recent: Clear Recent Files", "command": "clear_recent_files" },
]
```

Default (Windows).sublime-keymap
```
{ "keys": ["ctrl+k", "ctrl+h"], "command": "clear_recent_files" },
```

**Comment by TerminalFi** [comment]
Are you stating the command is not working or the documentation is wrong? 

Runnning `window.run_command("clear_recent_files")` should show you this is working.
