### ISSUE TITLE
Unable to escape regex open bracket '{' in tmPreferences 

### ISSUE THREAD

**Issue by leVoT8** [sublimetext-io/docs.sublimetext.io#58]
I'm currently working on a custom syntax, and editing the tmPreferences. When defining increaseIndentPattern regex, it includes an open bracket `{`. I attempt to escape it with `\` however sublime throws an error:

`error loading meta info from Packages/User/goku.tmPreferences: Expected element key`. 

Even copy + paste from sublime docs into tmPreferences throws the error. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Goku Preferences</string>
  <key>scope</key>
  <string>source.goku</string>
  <key>settings</key>
  <dict>
      <key>increaseIndentPattern</key>
      <string>\:\w+\s?\{</string>
  </dict>
  <dict>
    <key>shellVariables</key>
    <array>
      <dict>
        <key>name</key>
        <string>TM_COMMENT_START</string>
        <key>value</key>
        <string>; </string>
      </dict>
      <dict>
        <key>name</key>
        <string>TM_COMMENT_START_2</string>
        <key>value</key>
        <string>;*</string>
      </dict>
      <dict>
        <key>name</key>
        <string>TM_COMMENT_END_2</string>
        <key>value</key>
        <string>*;</string>
      </dict>
       <dict>
        <key>name</key>
        <string>TM_COMMENT_DISABLE_INDENT</string>
        <key>value</key>
        <string>no</string>
      </dict>
    </array>
  </dict>
  <key>uuid</key>
  <string>4ce04eed-6bf9-43db-81c8-576fdcbe5dca</string>
</dict>
</plist>
```

**Comment by FichteFoll** [comment]
That should generally work. So there might be something else going on, such as you made a syntax error earlier and then ST didn't properly reload the changes from disk or similar.

Regardless, this isn't the place to ask such questions. You'd better shoot these kind of question at the [forum](https://forum.sublimetext.com/) or the [discord](http://discord.sublimetext.io/).

**Comment by keith-hall** [comment]
FWIW, if you use PackageDev syntax highlighting, you'll see the problem is unrelated to the regex you are using. I'm guessing the `<dict>` before `shellVariables` is extraneous and causing the error you see.

**Comment by FichteFoll** [comment]
Thanks for taking another look. I missed this paragraph.

> Even copy + paste from sublime docs into tmPreferences throws the error.
