### ISSUE TITLE
Weird formatting in Commands Reference

### ISSUE THREAD

**Issue by rchl** [sublimetext-io/docs.sublimetext.io#66]
https://docs.sublimetext.io/reference/commands.html#commands

There is a colon starting the first paragraph of command description.
Is this some formatting marker that went wrong, convention or just a bug?

![Screenshot 2022-09-07 at 08 07 06](https://user-images.githubusercontent.com/153197/188801184-034e7c92-0aea-40b6-9aea-9ea0e819f697.png)

**Comment by FichteFoll** [comment]
I mentioned this on Discord, but this used to work and is supposed to translate the sections into `dd` and `dt` tags.

**Comment by FichteFoll** [comment]
This was caused by #41, where the command names where changed to use h3 tags to make them linkable via anchors but the `\n: ` syntax to create definition lists was not removed. I'll fix this.
