### ISSUE TITLE
New chapter about "arithmetics"

### ISSUE THREAD

**Issue by kitzberger** [sublimetext-io/docs.sublimetext.io#67]
Stumbled upon this cool yet undocumented feature yesterday:
* Create multiple selections
* `ctrl` + `shift` + `p` and enter "Arithmetic"
* enter an expression like:
  * `1+i` to create numbers like 1,2,3,4,5,6,7,8,9,...
  * `30+(i%3)` to create numbers like 30,31,32,30,31,32,33,...

**Comment by michaelblyons** [comment]
I believe `x` is also special, and does something slightly different than `i`.

**Comment by kitzberger** [comment]
@michaelblyons, yah, you're right. Have a look at my PR ;-)

**Comment by kitzberger** [comment]
@BenjaminSchaaf, sure about `z`?

Added some more examples to the PR.
