### ISSUE TITLE
Chromium on Linux does not render bold text

### ISSUE THREAD

**Issue by FichteFoll** [sublimetext-io/docs.sublimetext.io#9]
On my machine (Arch Linux), neither Chromium nor Vivaldi render bold text. The CSS selectors set `font-weight: 500` (links) or `600` (string tags) respectively, but they are rendered like normal text. This also applies to headings such as h5, which is by the way even smaller than the normal text size and that really shouldn't happen.

The same problem also exists in the default vuepress theme, so it's likely an upstream issue, but I wanted to track it regardless until I find out *which* upstream repo I should take this to.

**Comment by TerminalFi** [comment]
@FichteFoll can you confirm if this issue is present ?

**Comment by FichteFoll** [comment]
No, it works as expected on the current vitepress site.
